# Generated by Django 2.1.5 on 2019-04-15 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20190413_0104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(max_length=5000)),
                ('name', models.CharField(max_length=90)),
                ('email', models.CharField(max_length=130)),
                ('address', models.CharField(max_length=1500)),
                ('city', models.CharField(max_length=130)),
                ('state', models.CharField(max_length=130)),
                ('zip_code', models.CharField(max_length=100)),
            ],
        ),
    ]
